FROM python:3.14@sha256:0ba001803c72c128063cfa88863755f905cefabe73c026c66a5a86d8f1d63e98
EXPOSE 8391

WORKDIR /app

COPY internal/test/integration/components/pythonasync-uvloop/requirements-3.9.txt .
RUN pip install --require-hashes -r requirements-3.9.txt

COPY internal/test/integration/components/pythonasync-uvloop .

CMD ["python", "async_context_test.py"]
