FROM ruby:3.4.9@sha256:b366bf9c5c46cb2111e93cbc8a22e76150caf1a182cb90a86d5c5df108c307ed AS builder

WORKDIR /build

ENV BUNDLE_PATH=/usr/local/bundle

COPY internal/test/integration/components/rubytestserver/testapi .
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5 Gemfile
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5.lock Gemfile.lock

RUN gem install bundler -v 2.2.22
RUN bundle _2.2.22_ install
RUN bundle exec rake app:update:bin
RUN bundle exec rake db:migrate

FROM ruby:3.4.9-slim@sha256:756f37e6d559e7a081ff430be227efdce614047d8c7498a5795480545421b2fe

WORKDIR /

ENV BUNDLE_PATH=/usr/local/bundle

COPY --from=builder /build .
COPY --from=builder /usr/local/bundle /usr/local/bundle

EXPOSE 3040

CMD [ "bundle", "exec", "rails", "server", "-p", "3040", "-b", "0.0.0.0" ]
